feat: refactor run script

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,26 +1,36 @@
 #!/bin/sh
 
-__ARG=$1
+check_node_version() {
+  node_version=$(node -v | cut -c 2-)
+  if [ "$(printf '%s\n' "14" "$node_version" | sort -V | head -n1)" = "14" ]; then
+    echo >&2 "Node.js version 14 or above is installed. Continuing..."
+  else
+    echo >&2 "Node.js version 14 or above is required. Exiting..."
+    exit 1
+  fi
+}
+check_node_version
 
-__INIT="init"
-__START_LOCAL_DOCKER="start:docker"
-__STOP_LOCAL_DOCKER="stop:docker"
-__START_REACT="start:react"
-__UPDATE_CORE_LIB="update:core"
+kill_all_processes() {
+  echo "\n**Attempting a graceful shutdown**"
+  kill -15 "$PID_1" &&
+  echo "**Successfully terminated Core Library process [$PID_1]**"
+  kill -15 "$PID_2" &&
+  echo "**Successfully terminated React process [$PID_2]**"
+  rm -rf local.dev.log &&
+  echo "**Successfully deleted log file at [./local.dev.log]**"
+  exit 0
+}
 
-__CURRENT_UID=$(id -u):$(id -g)
-export __CURRENT_UID
-
-if [[ "$__ARG" == "$__INIT" ]]; then
+if [[ "$1" == "init" ]]; then
     shift
     cd core \
     && npm i \
     && cd ../web \
     && npm i \
+    && npm link ../core \
     && cd ..
-fi
-
-if [[ "$__ARG" == "$__START_LOCAL_DOCKER" ]]; then
+elif [[ "$1" == "docker:start" ]]; then
     shift
     if [[ "$(docker images -q hiramlabs/openresty 2> /dev/null)" == "" ]]; then
         docker build -t hiramlabs/openresty "$@" .
@@ -32,21 +42,17 @@ if [[ "$__ARG" == "$__START_LOCAL_DOCKER" ]]; then
         --name openresty \
         --restart=unless-stopped \
         hiramlabs/openresty
-fi
-
-if [[ "$__ARG" == "$__STOP_LOCAL_DOCKER" ]]; then
+elif [[ "$1" == "docker:stop" ]]; then
     shift
     docker stop "$@" openresty
-fi
-
-if [[ "$__ARG" == "$__START_REACT" ]]; then
+elif [[ "$1" == "dev:start" ]]; then
     shift
-    npm --prefix web run start
-fi
-
-if [[ "$__ARG" == "$__UPDATE_CORE_LIB" ]]; then
-    shift
-    npm --prefix core run build \
-    && mkdir -p ./web/src/lib/armulator_core \
-    && cp -a ./core/dist/*modern* ./web/src/lib/armulator_core
+    trap kill_all_processes INT TERM QUIT
+    npm --prefix core run dev --color=always 2>&1 >>local.dev.log &
+    PID_1=$!
+    npm --prefix  web run start --color=always 2>&1 >>local.dev.log &
+    PID_2=$!
+    tail -f local.dev.log
+else
+  echo >&2 "Invalid or no argument(s) provided for run."
 fi
